### ISSUE TITLE
Pitch bend

### ISSUE THREAD

**Issue by martin-minovski** [schellingb/TinySoundFont#10]
Would it be feasible to add pitch bend control for each note (defined by preset and pitch)?

Thanks

Martin

**Comment by schellingb** [comment]
Hi there again

Would something along these lines do the trick for you?
```c++
tsf_note_on_with_pitch(tsf* f, int preset_index, int key, float vel, int pitch_wheel_pos);
tsf_move_pitch_wheel(tsf* f, int preset_index, int pitch_wheel_pos);
```
I'm still not sure about what to do with note_on_* functions though. If there is also a variation with passing of panning factors from #8 it would get convoluted quickly (8 variations total). Maybe we can do something like
```c++
tsf_note_on_ex(tsf, 0, 60, 1.0, tsf_notesetting_pitchwheel(8192));
tsf_note_on_ex(tsf, 0, 60, 1.0, tsf_notesetting_panning(.3f, .7f));
tsf_note_on_ex(tsf, 0, 60, 1.0, tsf_notesetting_panning_pitchwheel(.3f, .7f, 8192));
```
Or maybe it would make more sense to do the adjustments after the note_on call but that would be sad because it would need to loop through all voices again. Or just move tsf_voice into the public API and have user code deal with it but that would be super inconvenient.

Do you have any feelings on that or are you fine if it just works somehow? :-)

**Comment by kavika13** [comment]
> maybe it would make more sense to do the adjustments after the note_on call
I think this might be necessary, since pitch bends can come at a time after a note has been struck and sustained for a while. At least if generalized midi playback is a goal

**Comment by schellingb** [comment]
Yeah I started a few implementations on various levels and in the end I think it needs a channel based interface to be usable. Here's what I have so far. It would be nice to have some more functionality for other controllers like modulation wheel, sustain and portamento and other switches but maybe that will have to wait.

```C
// Higher level channel based functions, set up channel parameters
//   preset_index: preset index >= 0 and < tsf_get_presetcount()
//   bank: instrument bank number (alternative to preset_index)
//   preset_number: preset number (alternative to preset_index)
//   channel: channel number
//   pitch_wheel: pitch wheel position 0 to 16383 (default 8192 unpitched)
//   pan: stereo panning value from 0.0 (left) to 1.0 (right) (default 0.5 center)
//   volume: linear volume scale factor
//   (set_bank_preset returns 0 if preset does not exist, otherwise 1)
TSFDEF void tsf_channel_set_preset(tsf* f, int channel, int preset_index);
TSFDEF int  tsf_channel_set_bank_preset(tsf* f, int channel, int bank, int preset_number);
TSFDEF void tsf_channel_set_pitchwheel(tsf* f, int channel, int pitch_wheel);
TSFDEF void tsf_channel_set_pan(tsf* f, int channel, float pan);
TSFDEF void tsf_channel_set_volume(tsf* f, int channel, float volume);

// Start or stop playing notes on a channel (needs channel preset to be set)
//   channel: channel number
//   key: note value between 0 and 127 (60 being middle C)
//   vel: velocity as a float between 0.0 (equal to note off) and 1.0 (full)
TSFDEF void tsf_channel_note_on(tsf* f, int channel, int key, float vel);
TSFDEF void tsf_channel_note_off(tsf* f, int channel, int key);
TSFDEF void tsf_channel_note_off_all(tsf* f, int channel);

// Get current values set on the channels
TSFDEF int tsf_channel_get_preset_index(tsf* f, int channel);
TSFDEF int tsf_channel_get_preset_bank(tsf* f, int channel);
TSFDEF int tsf_channel_get_preset_number(tsf* f, int channel);
TSFDEF int tsf_channel_get_pitchwheel(tsf* f, int channel);
TSFDEF float tsf_channel_get_pan(tsf* f, int channel);
TSFDEF float tsf_channel_get_volume(tsf* f, int channel);
```

**Comment by schellingb** [comment]
So... I committed this just now 40d48401892ddcb0a196dbcbea9261b92bfcf3c5.
The example3 is updated as well now with support for channel based panning, volume and pitch wheel changes.
As mentioned above, no other wheels or switches are supported for now.
I leave this open for a while if someone has any feedback.

**Comment by kavika13** [comment]
I won't be able to for about a week and a half since I'm going on vacation, but I'll check it out when I get back!

**Comment by martin-minovski** [comment]
Works here as well !! Test vid:
https://www.youtube.com/edit?o=U&video_id=oAF4Etf-Cqg
Million thanks :)
P.S. My new fav looper toy made with TSF: https://www.youtube.com/watch?v=eIlQNrAfSbA

**Comment by schellingb** [comment]
@zombaio Thanks a lot for testing!
@martin-minovski Thanks as well and that looks and sounds awesome! Really excited to see TSF used! :-)))
