### ISSUE TITLE
Play music in QBASIC's sequence format

### ISSUE THREAD

**Issue by paladin-t** [schellingb/TinySoundFont#2]
Hi,

I like this neat lib.

Is it possible to support playing music in [QBASIC's](https://en.wikibooks.org/wiki/QBasic/Appendix#PLAY) sequence format or something like that? Which is very nice to have.

**Comment by paladin-t** [comment]
Whatever, I did it myself.

[link](https://github.com/paladin-t/libtsf)

**Comment by schellingb** [comment]
Wow that was really quick!
I'm a bit busy these days so sorry for not getting back to you sooner.
Thanks for using the library and your improvements! Cool stuff!

I have never heard of the QBASIC music sequence stuff until now but I guess now I know how GORILLA.BAS played its music :-)

I'll merge the tsf_copy in the next few days I think it's useful.
And maybe I end up putting your tsf_play in as well, it seems reasonably small and useful and for people who don't use it it's not wasting anything.

**Comment by paladin-t** [comment]
Frankly, I was concerned if this lib is no longer maintained, before got your reply. I'm glad to make contribution, and really interested in its future evolvement.

For now it works fine, and I'll contact you when I got new ideas.

Cheers, and have a nice day!
