### ISSUE TITLE
Default tempo constant is set incorrectly

### ISSUE THREAD

**Issue by kavika13** [schellingb/TinySoundFont#29]
I think the constant `480000` in `tml_load`, for the default tempo value is incorrect.

This is supposed to be defined as microseconds per tick, and the default BPM is supposed to be 120, which means a value of `500000`.

This is the line of code that I think needs to be changed:
```
double ticks2time = 480000 / (1000.0 * division); //milliseconds per tick
```

Repro steps:

0. Grab this midi file that sets the BPM to 120 via SET_TEMPO messages, and never wavers from that tempo: [this midi file here - TITLE.zip](https://github.com/schellingb/TinySoundFont/files/2486307/TITLE.zip)
1. Playback the file and get the track length value: `tml_get_info(tiny_midi_loader, NULL, NULL, NULL, NULL, &time_length);`
2. Commented out the Set Tempo code in tml.h (inside `tml_load`):
```
if (Msg->type == TML_SET_TEMPO)
{
    //unsigned char* Tempo = ((struct tml_tempomsg*)Msg)->Tempo;
    //ticks2time = ((Tempo[0]<<16)|(Tempo[1]<<8)|Tempo[2])/(1000.0 * division);
    //tempo_msec = msec;
    //tempo_ticks = ticks;
}
```
3. Playback the same track with that code commented out, and get the track length value again

Expected:
The times in step 1 and step 3 should be equal

Actual:
The times are off by a factor of exactly `0.96` (480000 / 500000)

**Comment by schellingb** [comment]
According to https://www.csie.ntu.edu.tw/~r92092/ref/midi/#settempo
> If not specified, the default tempo is 120 beats/minute, which is equivalent to tttttt=500000 

Yeah 500000 seems to be the correct default.
Thanks again for this report and the pull request!!
