### ISSUE TITLE
Pitch Modulation

### ISSUE THREAD

**Issue by adrianmcroft** [schellingb/TinySoundFont#33]
So I'm going to attack adding Pitch Modulation from the Mod Wheel (well, vibrato) to my Bela implementation and wondered if anyone had already had a crack at this.

I presume that I'll have to implement controller ID #1 in tsf_channel_midi_control and link it to mod or vibLfoToPitch. Anyway, I'll start digging.

**Comment by adrianmcroft** [comment]
Ah never mind, I figured something out.

**Comment by tobybear** [comment]
Hi Adrian, I am currently in the process of adding this myself for my own project. :)
Do you mind sharing what you figured out?
