### ISSUE TITLE
[question] How to specify instrument bank?

### ISSUE THREAD

**Issue by frabert** [schellingb/TinySoundFont#6]
How would one specify which bank should a preset be chosen from?

**Comment by schellingb** [comment]
Hi there

Thanks for the question, I just added a function to look up the preset index by bank and preset number:
```c++
// Returns the preset index from a bank and preset number
// or -1 if it does not exist in the loaded SoundFont
int tsf_get_presetindex(const tsf* f, int bank, int preset_number);
```

I also added shortcuts to existing functions. Although these just call the lookup function above every time so performance-wise it might be useful to store the indexes somewhere.
```c++
const char* tsf_bank_get_presetname(const tsf* f, int bank, int preset_number);
void tsf_bank_note_on(tsf* f, int bank, int preset_number, int key, float vel);
void tsf_bank_note_off(tsf* f, int bank, int preset_number, int key);
```

Hope that works for you :-)
\ Bernhard

**Comment by frabert** [comment]
Thanks, much appreciated!
