### ISSUE TITLE
Would be possible to sustain a note?

### ISSUE THREAD

**Issue by ellipticaldoor** [schellingb/TinySoundFont#70]
When I play a note it will fade over time, but sometimes I want a note to be sustained more than what it does by default.

I looked at the source and I saw some references to sustain, though I could not find out how to tweak this parameter when I play sonud.

Could you help me to find a way to tell to tsf for how long I want to sustain a note?

**Comment by filipworksdev** [comment]
You can probably use a control change. https://nickfever.com/music/midi-cc-list

**Comment by ellipticaldoor** [comment]
@filipworksdev how I can use that? do you have an example?

**Comment by ellipticaldoor** [comment]
I remembered this comment https://github.com/schellingb/TinySoundFont/issues/56#issuecomment-817839274

And it worked perfectly
