### ISSUE TITLE
sfo file created with sfo_tool fails to load with tsf_load_memory.

### ISSUE THREAD

**Issue by SnowSnakz** [schellingb/TinySoundFont#90]
tsf_load_memory makes a call to tsf_load which ends in the following branch at Line 1423
```cpp
	else if (!rawBuffer && !floatBuffer)
	{
		// if (e) *e = TSF_INVALID_NOSAMPLEDATA;
	}
```

What I've tried:
* Loading and playing the original sf2 file, yes it works!
* Loading and playing the sfo file, it didn't work...

I've [attached these files (attachments.zip)](https://github.com/schellingb/TinySoundFont/files/15071920/attachments.zip) because it might help to resolve the issue:
* The original sf2
* sfotool's samples.wav output from the original sf2
* ogg data converted from the output wav data
* The sfo file from running the sf2 and ogg data through sfotool

I will also be doing to more debugging on my own, I will post updates if I find anything.

**Comment by schellingb** [comment]
As you've figured out, TSF just silently enables or disables OGG decoding support if a define from stb_vorbis is present or not (with the `#ifdef STB_VORBIS_INCLUDE_STB_VORBIS_H` at [tsf.h:865](../blob/master/tsf.h#L865)) and then silently at runtime fails (or succeeds) with a SoundFont that has OGG encoded samples.

We don't really have documentation for this stuff, not even an example, but I'm glad you were able to figure it out. Thanks for using TSF :-)
